custom_food_trailmix:
  type: item
  debug: false
  material: apple
  display name: <&a>Trail Mix
  data:
    amount: 8
    saturation: 10
  lore:
  - <&e>Hunger: <&f>8<&chr[0001].font[adriftus:foods]>
  - <&e>Saturation: <&f>10<&chr[0002].font[adriftus:foods]>
  mechanisms:
    custom_model_data: 1225
  recipes:
    1:
      type: shapeless
      input: cooking_tool_bakeware|custom_food_chocolatebar|custom_ingredient_saltitem|custom_seed_agaveseed/custom_seed_amaranthseed/custom_seed_arrowrootseed/custom_seed_artichokeseed/custom_seed_asparagusseed/custom_seed_barleyseed/custom_seed_beanseed/custom_seed_bellpepperseed/custom_seed_blackberryseed/custom_seed_blueberryseed/custom_seed_broccoliseed/custom_seed_brusselsproutseed/custom_seed_cabbageseed/custom_seed_cactusfruitseed/custom_seed_candleberryseed/custom_seed_cantaloupeseed/custom_seed_cassavaseed/custom_seed_cauliflowerseed/custom_seed_celeryseed/custom_seed_chickpeaseed/custom_seed_chilipepperseed/custom_seed_coffeebeanseed/custom_seed_cornseed/custom_seed_cottonseed/custom_seed_cranberryseed/custom_seed_cucumberseed/custom_seed_eggplantseed/custom_seed_elderberryseed/custom_seed_flaxseed/custom_seed_garlicseed/custom_seed_gingerseed/custom_seed_grapeseed/custom_seed_greengrapeseed/custom_seed_huckleberryseed/custom_seed_jicamaseed/custom_seed_juniperberryseed/custom_seed_juteseed/custom_seed_kaleseed/custom_seed_kenafseed/custom_seed_kiwiseed/custom_seed_kohlrabiseed/custom_seed_leekseed/custom_seed_lentilseed/custom_seed_lettuceseed/custom_seed_milletseed/custom_seed_mulberryseed/custom_seed_mustardseedsseed/custom_seed_oatsseed/custom_seed_okraseed/custom_seed_onionseed/custom_seed_parsnipseed/custom_seed_peanutseed/custom_seed_peasseed/custom_seed_pineappleseed/custom_seed_quinoaseed/custom_seed_radishseed/custom_seed_raspberryseed/custom_seed_rhubarbseed/custom_seed_riceseed/custom_seed_rutabagaseed/custom_seed_ryeseed/custom_seed_scallionseed/custom_seed_sesameseedsseed/custom_seed_sisalseed/custom_seed_soybeanseed/custom_seed_spiceleafseed/custom_seed_spinachseed/custom_seed_strawberryseed/custom_seed_sweetpotatoseed/custom_seed_taroseed/custom_seed_tealeafseed/custom_seed_tomatilloseed/custom_seed_tomatoseed/custom_seed_turnipseed/custom_seed_waterchestnutseed/custom_seed_whitemushroomseed/custom_seed_wintersquashseed/custom_seed_zucchiniseed|custom_crop_cherry/custom_crop_gooseberry/custom_crop_lemon/custom_crop_orange/custom_crop_peach/custom_crop_pear/custom_crop_plum/custom_crop_pawpaw/custom_crop_soursop/custom_crop_apricot/custom_crop_banana/custom_crop_date/custom_crop_dragonfruit/custom_crop_durian/custom_crop_fig/custom_crop_grapefruit/custom_crop_lime/custom_crop_mango/custom_crop_papaya/custom_crop_persimmon/custom_crop_pomegranate/custom_crop_starfruit/custom_crop_breadfruit/custom_crop_guava/custom_crop_jackfruit/custom_crop_lychee/custom_crop_passionfruit/custom_crop_rambutan/custom_crop_tamarind